app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class User(UserMixin, db.Model):
	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key = True)
	username = db.Column(db.String(20), unique = True, index = True)
	password_hash = db.Column(db.String(20))
	user_classifies = db.relationship('Classify', backref='user')

	@property
	def password(self):
		raise AttributeError('Password is not a readable attribute!')
		
	@password.setter
	def password(self, password):
		self.password_hash = generate_password_hash(password)
		
	def verify_password(self, password):
		return check_password_hash(self.password_hash, password) 
		
	@login_manager.user_loader
	def load_user(user_id):
		return User.query.get(int(user_id))	
	
	def __repr__(self):
		return '<User %r>' % self.username


class Classify(db.Model):
	__tablename__ = 'classifies'
	id = db.Column(db.Integer, primary_key = True)
	classify_name = db.Column(db.String(20))
	user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
	classify_notes = db.relationship('Note', backref='classify')
	
	def __repr__(self):
		return '<Classify %r>' % self.classify_name


class Note(db.Model):
	__tablename__ = 'notes'
	id = db.Column(db.Integer, primary_key = True)
	note_title = db.Column(db.String(50))
	note_content = db.Column(db.Text)
	classify_id = db.Column(db.Integer, db.ForeignKey('classifies.id'))
		
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField, TextAreaField
from wtforms.validators import InputRequired, ValidationError, Length
#~ from flask import flash
			
	
class CalssifyAddForm(FlaskForm):
	classify_add_name = StringField('分类名', 
		validators=[InputRequired(message='分类名不能为空'),
					Length(max=20,message='分类名不能超过20字符'),], 
		render_kw={"placeholder":"分类名"})
	classify_add_submit = SubmitField('确定')
					

class TitleAddForm(FlaskForm):
	classify_id = HiddenField('分类id')
	title_add_name = StringField('标题名', 
		validators=[InputRequired(message='标题名不能为空'),
					Length(max=20,message='标题名不能超过20字符'),], 
		render_kw={"placeholder":"标题名"})
	title_add_submit = SubmitField('确定')
	
			
class ContentAddForm(FlaskForm):
	classify_id = HiddenField('分类id')
	title_id = HiddenField('标题id')
	content_add_submit = SubmitField('保存')
	content_text = TextAreaField('内容') 						
			
			
			
			
			
			
			
			
			

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from config import config
from flask_login import LoginManager


db = SQLAlchemy()

bootstrap = Bootstrap()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
login_manager.login_message = '请登录后访问此页面'


def create_app(config_name):
	app = Flask(__name__)
	app.config.from_object(config[config_name])
	
	db.init_app(app)
	
	bootstrap.init_app(app)
	
	login_manager.init_app(app)
	
	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint)
	
	from .auth import auth as auth_blueprint
	app.register_blueprint(auth_blueprint)
	
	return app

app/main/__init__.py
from flask import Blueprint


main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from . import main
from .forms import CalssifyAddForm, TitleAddForm, ContentAddForm
from flask import render_template, request, redirect, url_for#~ from flask import session, flash
from flask_login import login_required, current_user
from ..models import db, Classify, Note


#分类区域：（添加分类表单,所有分类的分页对象）
def classify_area(classify_page):		
	user_id = current_user.get_id()					
	#分页对象	
	classify_pagination = Classify.query.filter_by(
		user_id=user_id).order_by(
		Classify.id.desc()).paginate(
		classify_page, per_page=10, error_out=False)
	if not classify_pagination.items:
		classify_pagination = Classify.query.filter_by(
			user_id=user_id).order_by(
			Classify.id.desc()).paginate(
			classify_page-1, per_page=10,error_out=False)
	classify_add_form = CalssifyAddForm()	
	return (classify_add_form,
			classify_pagination)

#分类区域路由
@main.route('/note/classify', methods=['GET', 'POST'])
@login_required
def classify():
	#删除分类
	classify_del_id = request.values.get('classify_del_id')
	if classify_del_id:
		classify_del = Classify.query.filter_by(id = classify_del_id).first()
		if classify_del:
			db.session.delete(classify_del)
			db.session.commit()
	#新增分类，未检测分类名
	classify_add_form = CalssifyAddForm()		
	user_id = current_user.get_id()
	classify_add_name = request.values.get('classify_add_name')
	#ajax提交表单，判断button的data值失效	
	#if add_form.add_submit.data and add_form.validate_on_submit():
	#ajax只提交数据，不进行validate
	if classify_add_name and classify_add_form.validate_on_submit():	
		classify_add = Classify()
		classify_add.classify_name = classify_add_name
		classify_add.user_id = user_id
		db.session.add(classify_add)
		db.session.commit()	
	#生成分类区域，必须放在最后，否则不是删除或者增加后的查询结果
	classify_page = request.values.get('classify_page_id', default=1, type=int)
	classify_add_form, classify_pagination = classify_area(classify_page)
	return render_template('classify.html',
							classify_add_form = classify_add_form,
							classify_pagination = classify_pagination)
							

#标题区域：（添加标题表单,所有标题的分页对象）
def title_area(classify_id, title_page):			
	title_pagination = Note.query.filter_by(
		classify_id=classify_id).order_by(
		Note.id.desc()).paginate(
		title_page, per_page=10, error_out=False)
	if not title_pagination.items:
		title_pagination = Note.query.filter_by(
			classify_id=classify_id).order_by(
			Note.id.desc()).paginate(
			title_page-1, per_page=1, error_out=False)						
	title_add_form = TitleAddForm()	
	return (title_add_form,
			title_pagination)
			
#标题区域路由			
@main.route('/note/title', methods=['GET', 'POST'])
@login_required
def title():
	#删除标题
	title_del_id = request.values.get('title_del_id')
	if title_del_id:
		title_del = Note.query.filter_by(id = title_del_id).first()
		if title_del:
			db.session.delete(title_del)
			db.session.commit()
	#新增标题，未检测标题
	title_add_form = TitleAddForm()
	classify_id = request.values.get('classify_id')
	title_add_name = request.values.get('title_add_name')
	if classify_id and title_add_name and title_add_form.validate_on_submit():	
		title_add = Note()
		title_add.note_title = title_add_name
		title_add.classify_id = classify_id
		db.session.add(title_add)
		db.session.commit()
	#生成标题区域，必须放在最后，否则不是删除或者增加后的查询结果	
	title_page = request.values.get('title_page_id', default=1, type=int)
	title_add_form, title_pagination = title_area(classify_id, title_page)
	title_add_form.classify_id.data = classify_id
	return render_template('title.html',
							title_add_form = title_add_form,
							title_pagination = title_pagination)


#内容区域：（保存内容表单）
def content_area(title_id):		
	note = Note.query.filter_by(id = title_id).first()	
	content_text = request.values.get('content_text')	
	if content_text:
		note.note_content = content_text
		db.session.add(note)
		db.session.commit()	
	content_add_form = ContentAddForm()	
	content_add_form.title_id = title_id
	content_add_form.content_text.data = note.note_content
	return content_add_form
			
#内容区域路由
@main.route('/note/content', methods=['GET', 'POST'])
@login_required
def content():
	title_id = request.values.get('title_id')
	content_add_form = content_area(title_id)
	return render_template('content.html', content_add_form = content_add_form)


#首页：分类第一页，标题区域空，内容区域空
@main.route('/note', methods=['GET', 'POST'])
@login_required
def note():	
	classify_add_form, classify_pagination = classify_area(classify_page=1)
	#~ 标题区域空
	#~ title_add_form, title_pagination = title_area(classify_id = None, title_page = 1)
	title_area = '请选择分类'
	#~ 内容区域空
	content_area = '请选择分类和笔记'						
	return render_template('note.html',
							classify_add_form = classify_add_form,
							classify_pagination = classify_pagination,
							title_area = title_area,
							content_area = content_area)



		

app/templates/base.html
{% extends "bootstrap/base.html" %}


{% block metas %}
{{ super() }}
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="X-UA-Compatible" content="IE=9" />
{% endblock %}


{% block styles %}
<link href="/static/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
{% endblock %}


{% block title %}云笔记{% endblock %}


{% block navbar %}
<div class = "navbar navbar-default" role = "navigation">
	<div class = "container">
		<div class = "navbar-header">
			<ul class = "nav">
				<li><a class = "navbar-brand" href = "/">
					<h4><span class="glyphicon glyphicon-home"></span>
					&nbsp;Home</h4></a>
				</li>
			</ul>
		</div>
		
		<div>
			<ul id="myTab" class = "nav nav-pills">
				<li><a href = "{{ url_for('main.note') }}">
					<h4><span class="glyphicon glyphicon-folder-open"></span>
					&nbsp;我的笔记</h4></a>
				</li>
				
				{% if current_user.is_authenticated %}
				<li class="navbar-right">	
					<a href="{{ url_for('auth.login') }}" class="text-primary">
					<h4><span class="glyphicon glyphicon-log-out"></span>
					&nbsp;退出</h4></a>
				</li>
				<li class="navbar-right">					
					<a href="{{ url_for('auth.modify') }}" class="text-warning">
					<h4><span class="glyphicon glyphicon-lock"></span>
					&nbsp;密码</h4></a>
				</li>
				{% else %}
				<li class="navbar-right">
					<a href="{{ url_for('auth.login') }}" class="text-primary">
					<h4><span class="glyphicon glyphicon-log-in"></span>
					&nbsp;登录</h3></a>					
				</li>
				<li class="navbar-right">
					<a href="{{ url_for('auth.reg') }}" class="text-warning">
					<h4><span class="glyphicon glyphicon-user"></span>
					&nbsp;注册</h4></a>
				</li>	
				{% endif %}					
			</ul>
		</div>
	</div>
</div>

{% endblock %}


{% block content %}
<div class = "container">
	{% for message in get_flashed_messages() %}
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>{{ message }}</strong>
    </div>
    {% endfor %}
	{% block page_content %}{% endblock %}
</div>
{% endblock %}


{% block scripts %}

<!--
解决ie9以下浏览器对html5新增标签的不识别，并导致CSS不起作用。
-->
<!--
解决ie9以下浏览器不支持css3 Media Query媒体查询。
-->
<!--[if lt IE 9]>
<script src="/static/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="/static/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<script src="/static/jquery/1.12.4/jquery.min.js"></script>
<script src="/static/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!--
导航栏当前链接设置active
-->
<script>
	$(document).ready(function(){
		$('.nav-pills').find('a').each(function(){
			if (this.href == document.location.href){
				$(this).parent().addClass('active');
				};
			});
	});
</script>

{% endblock %}












		

app/templates/classify.html
{% import "bootstrap/wtf.html" as wtf %}

<div id="classify_table">
	<table class="table table-hover" style="max-width:350px">
		<thead>
			<tr class="active">
				<th>	
					我的分类
				</th>		
				<th>	
					<button class="btn btn-xs btn-link"  data-toggle="modal" data-target="#classify_add" title="新分类">
						<span class="glyphicon glyphicon-plus">&nbsp;新分类</span>
					</button>
					<div class="modal fade" id="classify_add" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel_classify_add" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
									<h4 class="modal-title" id="myModalLabel_classify_add">
										<span class="glyphicon glyphicon-plus"></span>
										&nbsp;新分类</h4>
								</div>
								<div class="modal-body">{{ wtf.quick_form(classify_add_form,
									button_map={'classify_add_submit':'primary btn-block'},
									id="classify_add") }}
								</div>
								<div class="modal-footer">
								</div>
							</div>
						</div>
					</div>					
				</th>
			</tr>
		</thead>
		<tbody>				
		{% for p in classify_pagination.items %}
			<tr id="classify_tr" class="active">											
				<td style="width:320px">					
					<a id="classify_name" style="color:black;cursor:pointer;text-decoration:none;" value="{{ p.id }}" title="查看分类">
						{{ p.classify_name }}
					</a>					
				</td>										
				<td>
					<a id="classify_edit" style="cursor:pointer;" value="{{ p.id }}" title="修改分类名">
						<span class="glyphicon glyphicon-edit"></span>
					</a>
					&nbsp;&nbsp;																
					<a id="classify_del" style="cursor:pointer;" value="{{ p.id }}" title="删除分类">
						<span class="glyphicon glyphicon-trash"></span>
					</a>																
				</td>				
			</tr>		
		{% endfor %}
			<tr>
				<td colspan=2>
					<ul class="pagination">
						<li>
							<a id="classify_page" style="cursor:pointer;" value="{{ classify_pagination.page-1 }}" title="上一页">
								&lt;
							</a>
						</li>
						{% for p in classify_pagination.iter_pages(left_edge=1,left_current=1,right_current=2,right_edge=1) %}
						{% if p %}
							{% if p == classify_pagination.page %}
								<li id="classify_active" class="active" value="{{ p }}">
									<a id="classify_page" value="{{ p }}" style="cursor:pointer;" title="当前页">{{ p }}</a>
								</li>
							{% else %}
								<li>
									<a id="classify_page" value="{{ p }}" style="cursor:pointer;" title="第{{ p }}页">{{ p }}</a>
								</li>
							{% endif %}
						{% else %}
						<li><a>&hellip;</a></li>
						{% endif %}
						{% endfor %}
						<li>
							<a id="classify_page" style="cursor:pointer;" value="{{ classify_pagination.page+1 }}" title="下一页">
								&gt;
							</a>
						</li>
					</ul>
				</td>				
			</tr>
		</tbody>
	</table>
</div>		

app/templates/content.html
{% import "bootstrap/wtf.html" as wtf %}

<div id="content_table" value="{{ classify_id }}">
	{% if content_area %}
	{{ content_area }}
	{% else %}
	<table class="table table-hover" style="max-width:350px">
		<form id="content_add_form" method="POST">
		{{ content_add_form.hidden_tag() }}	
		<thead>
			<tr>
				<th>	
					{{ content_add_form.content_add_submit() }}
				</th>		
		</thead>
		<tbody>				
			<tr id="" class="active" value="">											
				<td style="width:320px">					
					{{ content_add_form.content_text(rows=25,cols=100) }}															
				</td>				
			</tr>
		</tbody>	
		</form>	
	</table>
	{% endif %}
</div>		

app/templates/main.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}在线笔记{% endblock %}


{% block page_content %}

<!--
<div class="page-header">

</div>
-->


<div class="container">	
	<table class="table table-hover">
		<thead>
			<tr>
				<th colspan=2>
					<button class="btn btn-xs btn-link" data-toggle="modal" data-target="#add" title="新分类">
						<span class="glyphicon glyphicon-plus">&nbsp;新分类</span>
					</button>
					<div class="modal fade" id="add" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="myModalLabel_add" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
									<h4 class="modal-title" id="myModalLabel_add">
										<span class="glyphicon glyphicon-plus"></span>
										&nbsp;新分类</h4>
								</div>
								<div class="modal-body">{{ wtf.quick_form(add_form,
									button_map={'add_submit':'primary btn-block'}) }}
								</div>
								<div class="modal-footer">
								</div>
							</div>
						</div>
					</div>						
				</th>
			</tr>
		</thead>
		<tbody>
		{% for classify_form in classify_forms %}	
			<tr>
<!--
				<td>
					{{ wtf.quick_form(classify_form,
						button_map={'classify_submit':'btm btn-primary btn-link'}) }}
				</td>
-->
				<form method="POST">
				<td>
					{{ classify_form.hidden_tag() }}
					{{ classify_form.classify_submit(class='btm btn-primary btn-link') }}
				</td>
				<td>
					{{ classify_form.del_submit() }}
				</td>
				</form>
			</tr>
		{% endfor %}
		</tbody>
	</table>					
</div>
{% endblock %}


{% block scripts %}
{{ super() }}

<script>
	$(document).ready(function(){
  $("button#del_button").click(function(){
    alert("确认删除？"+$(this).val())
  });
});
</script>

{% endblock %}

app/templates/note.html
{% extends "base.html" %}


{% block title %}云笔记{% endblock %}


{% block page_content %}
<div class="container">
	<table>
		<tbody>
			<tr>
				<td>
					<div id="classify_div">
						{% include 'classify.html' %}					
					</div>
				</td>
				<td>
					<div id="title_div">
						{% include 'title.html' %}	
				</td>
				<td>
					<div id="content_div">
						{% include 'content.html' %}	
				</td>				
			</tr>
		</tbody>
	</table>
</div>
{% endblock %}


{% block scripts %}
{{ super() }}
<script>
$(document).ready(function(){
  //禁用缓存，以获取修改后的结果
  $.ajaxSetup({cache: false});
  
  //删除分类
  $("div#classify_div").on("click","a#classify_del",function(){
	  var conf_del = confirm("删除分类将删除该分类的所有日记！\n\n确认删除？");
	  if (conf_del){
		  $.post("/note/classify",{classify_del_id:$(this).val(),classify_page_id:$("li#classify_active").val()},function(data,status){		  
			  $("div#classify_table").remove();
			  $("div#classify_div").html(data);			 
		  });
	  //load方法刚开始有延迟，后面的会有闪烁：
	  //$("div#table_div").remove();	$("div#classify").load("/note/classify",{del_id:$(this).val()}); 
	  };							  
  });
  //添加分类
  //click方法无法阻止回车键提交表单：$("input#add_submit").click(function(event){
  //submit方法不能给未来元素绑定方法：$("input#add_submit").submit(function(event){	  
  $("div#classify_div").on("submit","form#classify_add",function(event){
	  event.preventDefault();
	  $("div#classify_add").modal("hide");
	  //IE低版本不支持FormData：var  form_add = new FormData($("form#form_add")[0]); 
	  //只提交数据，不会经过validate：$.post("/note/classify",{add_name:$("input#add_name").val()},function(data,status){
	  //提交整个表单 
	  var classify_add_form=$(this).serialize();		  
	  $.post("/note/classify", classify_add_form, function(data,status){
		  $("div#classify_table").remove();
		  $("div#classify_div").html(data);
	  });
  });	
  //当前分类添加背景色，其他去除背景色
  $("div#classify_div").on("click","tr#classify_tr",function(){
	  $(this).addClass("info").siblings().removeClass("info");
  });
  //分类区域的分页
  $("div#classify_div").on("click","a#classify_page",function(event){
	  $.post("/note/classify",{classify_page_id:$(this).val()},function(data,status){
		  $("div#classify_table").remove();
		  $("div#classify_div").html(data);
	  });
  });
  //选择分类打开标题
  $("div#classify_div").on("click","a#classify_name",function(event){
	  $.post("/note/title",{classify_id:$(this).val()},function(data,status){
		  $("div#title_table").remove();
		  $("div#title_div").html(data);
	  });
  }); 
   
  //添加标题
  $("div#title_div").on("submit","form#title_add",function(event){
	  event.preventDefault();
	  $("div#title_add").modal("hide"); 
	  var title_add_form=$(this).serialize();			  
	  $.post("/note/title", title_add_form, function(data,status){
		  $("div#title_table").remove();
		  $("div#title_div").html(data);
	  });
  });  
  //删除标题
  $("div#title_div").on("click","a#title_del",function(){
	  var conf_del = confirm("删除日记将无法恢复！\n\n确认删除？");
	  if (conf_del){
		  $.post("/note/title",{title_del_id:$(this).val(),classify_id:$("tr#classify_id").val(),title_page_id:$("li#title_active").val()},function(data,status){		  
			  $("div#title_table").remove();
			  $("div#title_div").html(data);			 
		  });
	  }; 
  });   
  //标题区域的分页
  $("div#title_div").on("click","a#title_page",function(event){
	  $.post("/note/title",{title_page_id:$(this).val(),classify_id:$("tr#classify_id").val()},function(data,status){
		  $("div#title_table").remove();
		  $("div#title_div").html(data);
	  });
  });
  //选择标题打开内容
  $("div#title_div").on("click","a#title_name",function(event){
	  $.post("/note/content",{title_id:$(this).val()},function(data,status){
		  $("div#content_table").remove();
		  $("div#content_div").html(data);
	  });
  }); 
  //保存内容
  $("div#content_div").on("submit","form#content_add_form",function(event){
	  event.preventDefault();
	  var content_add_form=$(this).serialize();			  
	  $.post("/note/content", content_add_form, function(data,status){
		  $("div#content_table").remove();
		  $("div#content_div").html(data);
		  alert("保存笔记成功！")
	  });
  });  
  
  	   
});
</script>
{% endblock %}

app/templates/title.html
{% import "bootstrap/wtf.html" as wtf %}

<div id="title_table" value="{{ classify_id }}">
	{% if title_area %}
	{{ title_area }}
	{% else %}
	<table class="table table-hover" style="max-width:350px">
		<thead>
			<tr>
				<th>	
					我的笔记
				</th>		
				<th>	
					<button class="btn btn-xs btn-link"  data-toggle="modal" data-target="#title_add" title="新日记">
						<span class="glyphicon glyphicon-plus">&nbsp;新笔记</span>
					</button>
					<div class="modal fade" id="title_add" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel_title_add" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
									<h4 class="modal-title" id="myModalLabel_title_add">
										<span class="glyphicon glyphicon-plus"></span>
										&nbsp;新笔记</h4>
								</div>
								<div class="modal-body">{{ wtf.quick_form(title_add_form,
									button_map={'title_add_submit':'primary btn-block'},
									id="title_add") }}
								</div>
								<div class="modal-footer">
								</div>
							</div>
						</div>
					</div>					
				</th>
			</tr>
		</thead>
		<tbody>				
		{% for p in title_pagination.items %}
			<tr id="classify_id" class="active" value="{{ p.classify_id }}">											
				<td style="width:320px">					
					<a id="title_name" style="color:black;cursor:pointer;text-decoration:none;" value="{{ p.id }}" title="查看分类">
						{{ p.note_title }}
					</a>					
				</td>										
				<td>
					<a id="title_edit" style="cursor:pointer;" value="{{ p.id }}" title="修改标题">
						<span class="glyphicon glyphicon-edit"></span>
					</a>
					&nbsp;&nbsp;																
					<a id="title_del" style="cursor:pointer;" value="{{ p.id }}" title="删除日记">
						<span class="glyphicon glyphicon-trash"></span>
					</a>																
				</td>				
			</tr>		
		{% endfor %}
			<tr>
				<td colspan=2>
					<ul class="pagination">
						<li>
							<a id="title_page" style="cursor:pointer;" value="{{ title_pagination.page-1 }}" title="上一页">
								&lt;
							</a>
						</li>
						{% for p in title_pagination.iter_pages(left_edge=1,left_current=1,right_current=2,right_edge=1) %}
						{% if p %}
							{% if p == title_pagination.page %}
								<li id="title_active" class="active" value="{{ p }}">
									<a id="title_page" value="{{ p }}" style="cursor:pointer;" title="当前页">{{ p }}</a>
								</li>
							{% else %}
								<li>
									<a id="title_page" value="{{ p }}" style="cursor:pointer;" title="第{{ p }}页">{{ p }}</a>
								</li>
							{% endif %}
						{% else %}
						<li><a>&hellip;</a></li>
						{% endif %}
						{% endfor %}
						<li>
							<a id="title_page" style="cursor:pointer;" value="{{ title_pagination.page+1 }}" title="下一页">
								&gt;
							</a>
						</li>
					</ul>
				</td>				
			</tr>
		</tbody>
	</table>
	{% endif %}
</div>		